### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/jsonresume-theme-eloquent#1]
- [ ] Main menu
- [ ] New build system? https://github.com/remy/inliner/blob/master/inliner.js
- [ ] "Print this resume" button? http://css-tricks.com/quick-tip-making-a-print-this-page-button/
- [ ] Minify HTML? https://www.npmjs.com/package/html-minifier
- [ ] Generate item ids from text content?
